// <auto-generated />
using System;
using BikeAnalyzerDDD.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeAnalyzerDDD.Persistence.EF.Migrations
{
    [DbContext(typeof(BikeAnalyzerDDDContext))]
    [Migration("20221126192838_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeAnalyzerDDD.Domain.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("GeneralBikeRate")
                        .HasColumnType("float");

                    b.Property<double?>("HeadTubeAngle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("float");

                    b.Property<double?>("InnerRimWidth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double?>("SeatTubeEffectiveAngle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("float");

                    b.Property<double?>("TireWidth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("float");

                    b.Property<int?>("TravelBackWheel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int?>("TravelFrontWheel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<double?>("Weigth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("float");

                    b.Property<int?>("YearOfProduction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Scott",
                            HeadTubeAngle = 67.299999999999997,
                            InnerRimWidth = 30.0,
                            Model = "Spark RC World Cup Evo",
                            SeatTubeEffectiveAngle = 74.0,
                            TireWidth = 2.3999999999999999,
                            TravelBackWheel = 120,
                            TravelFrontWheel = 120,
                            Weigth = 10.300000000000001,
                            YearOfProduction = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scott",
                            HeadTubeAngle = 67.299999999999997,
                            InnerRimWidth = 30.0,
                            Model = "Spark RC World Cup",
                            SeatTubeEffectiveAngle = 74.0,
                            TireWidth = 2.3999999999999999,
                            TravelBackWheel = 120,
                            TravelFrontWheel = 120,
                            Weigth = 10.699999999999999,
                            YearOfProduction = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
